# Use root/example as user/password credentials
version: '3.3'

services:
  db:
    image: mysql:8.0.21
    volumes:
      - ./data/mysql:/var/lib/mysql
#      - ./mysql/init_schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    environment:
      MYSQL_USER: ppmtcourse
      MYSQL_PASSWORD: ppmtcourse_dev
      MYSQL_DATABASE: ppmtcourse
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
    - 3306:3306
#volumes:
#  db_data:
#    external:
#      name: mysql-data